### ISSUE TITLE
Can't enter manually the path for User data directory (Linux)

### ISSUE THREAD

**Issue by Mery042** [BigBang1112/randomizer-tmf#11]
Hello,

I'm able to select my Game data directory path but then it automatically fills a wrong path for User data directory "/home/remi/TrackMania".
Could you provide a button to select the user data directory too ?

Thanks a lot and great work !

**Comment by BigBang1112** [comment]
Hi, it is expected that the UserData of Randomizer should match the UserData specified by Nadeo.ini, which automatically includes MyDocuments directory, therefore this will not be worked on.
