### ISSUE TITLE
Potential HTTP API?

### ISSUE THREAD

**Issue by expected-ingot** [BigBang1112/randomizer-tmf#15]
Hey. I would like to create a TMNF/TMUF client for Archipelago, and I would like to use this to randomize maps or skip them. Is there a way to interact with the app? If not, are there plans to make one?

**Comment by BigBang1112** [comment]
Hello, I cannot find exactly what is Archipelago but external communication is not going to be supported until the official leaderboard features. This leaderboard feature (which will include centralized RMC sessions, web API and such) will happen depending on if it's gonna be possible to do RMC in the new TMUnlimiter.

**Comment by crapbass** [comment]
Ah, okay :) (this is archipelago btw: https://archipelago.gg/)
